### ISSUE TITLE
TypeError: forward() got multiple values for argument 'usecuda'

### ISSUE THREAD

**Issue by xiaxyun** [asiddhant/Active-NLP#3]
Traceback (most recent call last):
  File "active_ner.py", line 313, in <module>
    eval_test_train=False, plot_every = acq_plot_every, lr_decay = 0.05)
  File "F:\git\Active-NLP\neural_ner\util\trainer.py", line 77, in train_model
    score = self.model(words, tags, chars, caps, wordslen, charslen, mask, n_batches, usecuda=True)
  File "E:\Program Files\Python3.6\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got multiple values for argument 'usecuda'

why this error？when i run it

**Comment by xiaxyun** [comment]
i use the torch-0.4 ,so it appears this error!

**Comment by xiaxyun** [comment]
Can you send the dataset ontonotes? thank you very much!

**Comment by adisid001** [comment]
I cannot send the data or upload it because of ownership issues. If you however, get an approval from LDC and download the raw data, i can send you the code to preprocess that dataset in the format used in the code (similar to CoNLL).

**Comment by avinik** [comment]
> Traceback (most recent call last):
> File "active_ner.py", line 313, in 
> eval_test_train=False, plot_every = acq_plot_every, lr_decay = 0.05)
> File "F:\git\Active-NLP\neural_ner\util\trainer.py", line 77, in train_model
> score = self.model(words, tags, chars, caps, wordslen, charslen, mask, n_batches, usecuda=True)
> File "E:\Program Files\Python3.6\lib\site-packages\torch\nn\modules\module.py", line 491, in **call**
> result = self.forward(*input, **kwargs)
> TypeError: forward() got multiple values for argument 'usecuda'
> 
> why this error？when i run it

I am getting the same error. Can you explain how it can be solved.

**Comment by SeekPoint** [comment]
how to fix it? Does it caused by some data missing?

**Comment by avinik** [comment]
> how to fix it? Does it caused by some data missing?

No, There is no data missing. I fixed it by correcting some error in codes but i don't exactly remeber the errors now.You can see corrected code on my github profile where i have forked this repo.

**Comment by SeekPoint** [comment]
@avinik it's cool, thanks
